### ISSUE TITLE
Does not work for some links

### ISSUE THREAD

**Issue by gbip** [Kanabenki/cpc-link-crusher#1]
It seems that the extension does not work for some links.
For example, this page causes a problem :
https://homepages.laas.fr/huguet/drupal/content/m%C3%A9taheuristiques-4ir-info#overlay-context=content/m%25C3%25A9ta-heuristiques-4ir-info

**Comment by Kanabenki** [comment]
Closing as the [cpc.cx](https://cpc.cx) service is now closed to the public.
